### ISSUE TITLE
Benchmarks for piecetable vs rope comparison

### ISSUE THREAD

**Issue by matu3ba** [daurnimator/zig-piecetable#1]
Do you have any benchmarks or numbers to estimate when to use a piecetable and when a rope?

For example [in this retrospective](https://raphlinus.github.io/xi/2020/06/27/xi-retrospective.html) is the claim 
"Similarly, many good editors have been written using piece tables, but I’m not a huge fan; performance is very good when first opening the file, but degrades over time. My favorite aspect of the rope as a data structure is its excellent worst-case performance."

But I did not see yet data regarding performance of piecetable and rope in different situations.

**Comment by daurnimator** [comment]
> Do you have any benchmarks or numbers to estimate when to use a piecetable and when a rope?

No.

Given I don't have a rope implementation written in the same language or style, I don't think I can accomplish this in the context of this repository.
